import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";

/**
 * Render `assets/prompt-templates/*.md` as a TypeScript module.
 *
 * The templates are real markdown files because that is what they are for —
 * read, diffed, and edited by hand. But nothing bundles a `.md`: the VS Code
 * extension is one `extension.js`, the CLI is another, and an asset path
 * resolved off `__dirname` is a different guess in each and wrong in a
 * webview. Inlining sidesteps the question.
 *
 * Lives in the source tree rather than in `scripts/` so the drift test can
 * import it the same way the generator does, and the two cannot disagree about
 * what the generated file should look like.
 */
export function buildBuiltinTemplatesModule(dir: string): string {
	const files = readdirSync(dir)
		.filter((name) => name.endsWith(".md"))
		.sort();

	const entries = files
		.map((name) => {
			const body = readFileSync(join(dir, name), "utf8").replace(/\r\n/g, "\n");
			// A template is prose full of backticks, and `${` is plausible inside
			// one, so JSON is the only quoting that is safe without thinking.
			return `\t{\n\t\tfileName: ${JSON.stringify(name)},\n\t\traw: ${JSON.stringify(body)},\n\t},`;
		})
		.join("\n");

	// The drift test compares this string to the file byte for byte, which only
	// works because `*.generated.ts` is excluded from Biome in sdk/biome.json —
	// otherwise the formatter and the generator would each keep undoing the
	// other, and the test would fail on whichever ran second.
	return `// GENERATED by scripts/generate-builtin-templates.mts — do not edit.
//
// Source of truth is assets/prompt-templates/*.md. Edit those, then re-run the
// generator; \`builtin-templates.test.ts\` fails if the two disagree.

export interface BuiltinPromptTemplateFile {
	fileName: string;
	raw: string;
}

export const BUILTIN_PROMPT_TEMPLATE_FILES: readonly BuiltinPromptTemplateFile[] =
	[
${entries}
	];
`;
}
