export { CLINE_DEFAULT_MODEL_ID } from "@cline/shared";
export type {
	GetModelsForProviderOptions,
	ModelCollection,
	ModelIdAliasRule,
	ModelInfo,
	ModelInfo as CatalogModelInfo,
	ProviderCapability as CatalogProviderCapability,
	ProviderClient,
	ProviderInfo,
	ProviderModelFilter,
	ProviderProtocol,
} from "./models";
export {
	CODEX_EFFECTIVE_CONTEXT_WINDOW_PERCENT,
	fetchLiveProviderModels,
	fetchModelsDevProviderModels,
	filterImageOutputModels,
	filterOpenAICodexModels,
	getAllProviders,
	getGeneratedModelsForProvider,
	getGeneratedProviderModels,
	getModelOverridesForProvider,
	getModelsForProvider,
	getProvider,
	getProviderCollection,
	getProviderCollectionSync,
	getProviderIds,
	hasProvider,
	isCanonicalModelIdForAliasRules,
	MODEL_COLLECTIONS_BY_PROVIDER_ID,
	preferCanonicalModelIds,
	registerModel,
	registerProvider,
	resetRegistry,
	sortModelsByReleaseDate,
	unregisterModel,
	unregisterProvider,
	VERCEL_OPENROUTER_MODEL_ID_ALIAS_RULES,
} from "./models";
export type {
	ApiHandler,
	ApiStreamChunk,
	BuiltInProviderId,
	ContentBlock,
	FileContent,
	HandlerFactory,
	HandlerModelInfo,
	ImageContent,
	LazyHandlerFactory,
	Message,
	MessageRole,
	MessageWithMetadata,
	PolykvOptions,
	ProviderCapability,
	ProviderConfig,
	ProviderId,
	ProviderSamplingOptions,
	RedactedThinkingContent,
	TextContent,
	ThinkingContent,
	ToolDefinition,
	ToolResultContent,
	ToolUseContent,
} from "./providers";
export {
	BUILT_IN_PROVIDER,
	BUILT_IN_PROVIDER_IDS,
	ClineFreeModelLimitError,
	ClineNotSubscribedError,
	ClineOrgIndividualInferenceSubscriptionError,
	ClinePassLimitError,
	classifyProviderError,
	createHandler,
	createHandlerAsync,
	extractClineFreeModelLimitResetTime,
	extractClinePassLimitMessage,
	getClineNotSubscribedMessage,
	getClineOrgIndividualInferenceSubscriptionMessage,
	getClinePassSubscriptionUrl,
	getRegisteredHandler,
	getRegisteredHandlerAsync,
	// A host that bundles has to hand the Ollama vendor its stream dispatcher:
	// the vendor's own lookup is written to be invisible to bundlers, so it
	// finds nothing once packaged.
	hasOllamaFetch,
	hasOllamaNoStreamTimeoutDispatcher,
	hasRegisteredHandler,
	isBuiltInProviderId,
	isClineFreeModelLimitError,
	isClineFreeModelLimitMessage,
	isClineModelNotFoundMessage,
	isClineNotSubscribedError,
	isClineNotSubscribedMessage,
	isClineOrgIndividualInferenceSubscriptionError,
	isClineOrgIndividualInferenceSubscriptionMessage,
	isClinePassLimitError,
	isClinePassLimitMessage,
	isProviderApiLine,
	isRegisteredHandlerAsync,
	looksLikeCloudName,
	matchOllamaRecommendation,
	normalizeProviderId,
	OLLAMA_DEFAULT_CONTEXT_WINDOW,
	OLLAMA_DEFAULT_REASONING_EFFORT,
	type OllamaAccount,
	type OllamaAccountStatus,
	type OllamaCatalogEntry,
	type OllamaRecommendation,
	type ProviderApiLine,
	primeDeclaredNumCtx,
	primeOllamaAccountStatus,
	readDeclaredFamily,
	readDeclaredNumCtx,
	readDeclaredTemperature,
	readOllamaAccountCache,
	readOllamaAccountStatus,
	readOllamaCloudFlag,
	readOllamaRecommendation,
	readResolvedOllamaWindow,
	registerAsyncHandler,
	registerHandler,
	resolveProviderApiLineBaseUrl,
	setOllamaFetch,
	setOllamaNoStreamTimeoutDispatcher,
} from "./providers";
export {
	type AgentSlotLimit,
	DEFAULT_PARALLEL_SESSIONS,
	MAX_PARALLEL_SESSIONS,
	MIN_PARALLEL_SESSIONS,
	normalizeParallelSessions,
	resolveAgentSlotLimit,
} from "./providers/agent-slots";
export {
	type ProviderUsageCostDisplay,
	resolveProviderUsageCostDisplay,
	shouldShowProviderUsageCost,
} from "./providers/billing";
export type * from "./providers/gateway";
export {
	createGateway,
	DEFAULT_GATEWAY_MAX_OUTPUT_TOKENS,
	DefaultGateway,
	resolveDefaultMaxOutputTokens,
} from "./providers/gateway";
export { toGatewayModelCapabilities } from "./providers/model-capabilities";
export {
	type ReasoningHistoryMode,
	reasoningHistoryModeForProvider,
} from "./providers/model-facts";
export {
	BUILTIN_MODEL_OPERATION_CAPABILITIES,
	builtinProviderSupportsModelOperation,
	providerManifestSupportsModelOperation,
	resolveModelOperation,
} from "./providers/model-operations";
export {
	type ModelToolSupportInput,
	providerManifestSupportsModelTool,
	providerOffersModelTool,
	supportsModelTool,
} from "./providers/model-tools";
export { resolveProviderModelCatalogKeys } from "./providers/provider-keys";
export {
	type OpenAICodexRequestHeaderContext,
	type ProviderRequestHeaderClientContext,
	type ProviderRequestHeaderLayers,
	type ResolveProviderRequestHeadersInput,
	resolveProviderRequestHeaders,
} from "./providers/request-headers";
export {
	probeServerHealth,
	SERVER_HEALTH_FIRST_INTERVAL_MS,
	SERVER_HEALTH_MAX_INTERVAL_MS,
	SERVER_HEALTH_PROBE_TIMEOUT_MS,
	serverHealthBackoffMs,
	serverRoot,
	sleepUnlessAborted,
	waitForServerHealth,
} from "./providers/server-health";
export {
	type ClineProvider,
	type ClineProviderOptions,
	type ClineWebSearchInput,
	type ClineWebSearchOptions,
	type ClineWebSearchResult,
	createCline,
} from "./providers/vendors/cline";
export {
	buildLlamaCppSamplingOptions,
	LLAMACPP_SAMPLING_WIRE_NAMES,
	LLAMACPP_THINK_BUDGET_FRACTION,
	readLlamaCppSamplingOptions,
	resolveLlamaCppThinkBudgetTokens,
	resolveLlamaCppThinkBudgetWindow,
} from "./providers/vendors/llamacpp-sampling";
export {
	getOpencotiWindowCeiling,
	getOpencotiWindowFloor,
	latestOpencotiPressure,
	noteOpencotiPressure,
	noteOpencotiRefusalPressure,
	OPENCOTI_PRESSURE_CLEAR_MAX_AGE_MS,
	type OpencotiKvPressure,
	type OpencotiKvResident,
	type OpencotiKvSnapshot,
	type OpencotiKvSwa,
	type OpencotiPressureReading,
	type OpencotiResizeDone,
	type OpencotiResizeRefused,
	type OpencotiResizeResult,
	opencotiPendingResize,
	opencotiPressureState,
	opencotiRefusalsAreGlobal,
	opencotiResizeRequest,
	parseOpencotiKvPressure,
	parseOpencotiRefusalPressure,
	readOpencotiKv,
	recordOpencotiWindowCeiling,
	recordOpencotiWindowFloor,
	resetOpencotiPendingResizes,
	resetOpencotiPressure,
	resetOpencotiWindowCeilings,
	resetOpencotiWindowFloors,
	resizeOpencotiSession,
} from "./providers/vendors/opencoti-kv-pressure";
export {
	describeOpencotiStreamPhase,
	OPENCOTI_KEEPALIVE_PING_SECONDS,
	OpencotiServerSilentError,
	type OpencotiStreamPhase,
	opencotiKeepaliveDeadMs,
} from "./providers/vendors/opencoti-liveness";
export {
	formatWindowK,
	isOpencotiWindowUnavailableError,
	OPENCOTI_WINDOW_UNAVAILABLE_CODE,
	type OpencotiWindowUnavailableDetails,
	OpencotiWindowUnavailableError,
	parseOpencotiWindowUnavailable,
} from "./providers/vendors/opencoti-window";
export {
	clearPolykvGrantedWindow,
	clearPolykvSession,
	createPolykvClient,
	getPolykvGrantedWindow,
	getPolykvSession,
	getPolykvWindowGrant,
	getPolykvWindowObservation,
	hasOpencotiFeature,
	OPENCOTI_FEATURES,
	type OpencotiAllocation,
	type OpencotiFeature,
	type OpencotiStatus,
	type OpencotiStatusPool,
	type OpencotiStatusSession,
	onPolykvWindowGrant,
	type PolykvCapacity,
	type PolykvClient,
	type PolykvClientOptions,
	type PolykvPool,
	PolykvSaturatedError,
	type PolykvSessionState,
	type PolykvWindowGrant,
	type PolykvWindowObservation,
	polykvEffectiveWindow,
	polykvRoot,
	probeOpencotiProps,
	probePolykvEnabled,
	readOpencotiAllocations,
	readOpencotiDefaultTemperature,
	readOpencotiStatus,
	readPolykvWindowGrant,
	recordPolykvGrantedWindow,
	recordPolykvWindowObservation,
	resetPolykvAvailability,
	resetPolykvSessions,
	setPolykvSession,
} from "./providers/vendors/polykv";
export {
	hoistLeadEnvironment,
	type LeadAttach,
	markLeadWindowLive,
	POLYKV_LEAD_RECHECK_MS,
	polykvLeadState,
	prepareLeadPool,
	releaseAllPolykvLeads,
	releasePolykvLead,
} from "./providers/vendors/polykv-lead";
export {
	deferPolykvLeadClose,
	engineSessionId,
	growPolykvOwnerForWorker,
	invalidatePolykvRoot,
	isWorkerWindowFull,
	notePolykvBootId,
	notePolykvOwnerWindow,
	notePolykvServerFault,
	onPolykvNotice,
	onPolykvRoomWait,
	onPolykvStreamPhase,
	POLYKV_LEAD_SUBPOOL_CAP,
	POLYKV_LEAD_WORKER_POOL_MAX,
	POLYKV_OWNER_MIN_WINDOW,
	POLYKV_PHASE_REPORT_MS,
	POLYKV_ROOM_BACKOFF_MAX_MS,
	POLYKV_VERIFY_INTERVAL_MS,
	type PolykvLeadRoom,
	type PolykvNotice,
	type PolykvReleaseResult,
	type PolykvRoomWait,
	type PolykvWorkerAttach,
	type PolykvWorkerSpec,
	parseWorkerWindowFull,
	polykvLeadLent,
	polykvLeadReserveCells,
	polykvOwnerAgentCapacity,
	polykvOwnerBooking,
	polykvOwnerWindowBounds,
	polykvRoomBackoffMs,
	polykvRootGeneration,
	polykvServerIdentity,
	polykvSwarmState,
	polykvWorkerChargedTo,
	preparePolykvWorker,
	readPolykvLeadRoom,
	releaseAllPolykvSwarms,
	releasePolykvAgent,
	rememberOpencotiSession,
	reportPolykvNotice,
} from "./providers/vendors/polykv-swarm";
export { disposeLangfuseTelemetry } from "./services/langfuse-telemetry";
export {
	type AudioTranscriptionRequest,
	type AudioTranscriptionResult,
	type AudioTranscriptionRoute,
	createStreamingAudioTranscriptionSession,
	DEFAULT_TRANSCRIPTION_TIMEOUT_MS,
	resolveAudioTranscriptionRoute,
	type StreamingAudioTranscriptionSession,
	type StreamingAudioTranscriptionSessionRequest,
	transcribeAudio,
} from "./transcription";
