#!/usr/bin/env bash
# Rebuild the vendored office_oxide WebAssembly module.
#
# npm's `office-oxide-wasm` stops at 0.1.8, which has no image extraction and
# cannot even be loaded by Node: its package says "type": "module" while its
# node/ entry is CommonJS. The Rust crate is where the legacy .doc/.xls/.ppt
# readers were reworked (0.1.12), so the module is built from a pinned tag.
#
# Needs cargo with the wasm32-unknown-unknown target, and wasm-bindgen-cli at
# the version the crate's Cargo.lock names (the script checks).
#
#   rustup target add wasm32-unknown-unknown
#   cargo install wasm-bindgen-cli --version <version> --locked
#
# Writes:
#   assets/office-oxide/office_oxide_bg.wasm        the module
#   src/extensions/tools/executors/document/office-oxide.generated.ts
#                                                   wasm-bindgen's glue
set -euo pipefail

TAG="${OFFICE_OXIDE_TAG:-v0.1.12}"
CORE="$(cd "$(dirname "$0")/.." && pwd)"
WORK="$(mktemp -d "${OFFICE_OXIDE_WORKDIR:-${TMPDIR:-/tmp}}/office-oxide.XXXXXX")"
trap 'rm -rf "$WORK"' EXIT

git clone -q --depth 1 --branch "$TAG" https://github.com/yfedoseev/office_oxide.git "$WORK/src"
COMMIT="$(git -C "$WORK/src" rev-parse HEAD)"

WANT="$(awk '/^name = "wasm-bindgen"$/{getline; gsub(/[^0-9.]/,""); print; exit}' "$WORK/src/Cargo.lock")"
HAVE="$(wasm-bindgen --version | awk '{print $2}')"
if [ "$WANT" != "$HAVE" ]; then
	echo "wasm-bindgen $HAVE installed, the crate needs $WANT:" >&2
	echo "  cargo install wasm-bindgen-cli --version $WANT --locked" >&2
	exit 1
fi

(cd "$WORK/src" && CARGO_TARGET_DIR="$WORK/target" cargo build --release --lib \
	--target wasm32-unknown-unknown --features wasm)
wasm-bindgen --target web --out-dir "$WORK/out" \
	"$WORK/target/wasm32-unknown-unknown/release/office_oxide.wasm"

mkdir -p "$CORE/assets/office-oxide"
cp "$WORK/out/office_oxide_bg.wasm" "$CORE/assets/office-oxide/"
cp "$WORK/src/LICENSE-MIT" "$WORK/src/LICENSE-APACHE" "$CORE/assets/office-oxide/"

GLUE="$CORE/src/extensions/tools/executors/document/office-oxide.generated.ts"
{
	echo "// @ts-nocheck"
	echo "// Generated by scripts/build-office-oxide.sh from office_oxide $TAG ($COMMIT)."
	echo "// Do not edit. MIT OR Apache-2.0, see assets/office-oxide/."
	echo "//"
	echo "// The async initializer's default path is removed: it resolves the module"
	echo "// against the module's own URL and fetches it, neither of which survives bundling into"
	echo "// the extension. The module is loaded with initSync from bytes instead."
	sed "s#module_or_path = new URL('office_oxide_bg.wasm', import.meta.url);#throw new Error('office_oxide: load the module with initSync');#" \
		"$WORK/out/office_oxide.js"
} > "$GLUE"
if grep -v "^//" "$GLUE" | grep -q "import\.meta"; then
	echo "the glue still reads import.meta; the wasm-bindgen output changed shape" >&2
	exit 1
fi
echo "office_oxide $TAG ($COMMIT) -> $CORE/assets/office-oxide, $GLUE"
