/**
 * Ask a model to rewrite its own prompt template.
 *
 * The shipped templates are written by us, against failures we watched happen.
 * That is a reasonable starting point and a poor stopping point: the whole
 * premise of per-family templates is that a Gemma reads differently from a
 * Qwen, and the model that knows most about how Gemma reads is a Gemma. So
 * this hands a model the template it would actually be given, tells it what
 * goes wrong in practice, and asks for a version in the form it would rather
 * receive.
 *
 * Runs against Ollama's cloud models, which are large enough to be worth
 * asking and are reached through the same local endpoint as everything else:
 *
 *   bun scripts/review-prompt-templates.mts
 *   bun scripts/review-prompt-templates.mts --model glm-5.3:cloud
 *   bun scripts/review-prompt-templates.mts --all
 *   OLLAMA_HOST=http://pandorum:11439 bun scripts/review-prompt-templates.mts
 *
 * What comes back is a proposal, not a template. It is parsed and validated
 * before being written, so a review that produced something Cline cannot load
 * says so here rather than at the next session start, and nothing is copied
 * into `assets/` automatically — that stays a human decision.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
	DEFAULT_PROMPT_TEMPLATE_NAME,
	renderPromptTemplate,
} from "@cline/shared";
import { getBuiltinPromptTemplates } from "../src/extensions/config/builtin-templates";
import { generatePromptTemplate } from "../src/extensions/config/prompt-template-review";
import { getShippedToolCallSignatures } from "../src/extensions/config/shipped-tool-signatures";

const here = dirname(fileURLToPath(import.meta.url));
const TEMPLATE_DIR = join(here, "..", "assets", "prompt-templates");
/**
 * Proposals are never written to `prompt-reviews/` itself. That directory is
 * the *current* set -- one file per family, named for the family, because the
 * parser falls back to the filename for a template's name
 * (`prompt-template-parser.ts`). A generator that wrote there would overwrite
 * the accepted template with an unreviewed proposal, which is how the
 * directory ended up holding six stale files and five loose logs.
 *
 * Every run writes to `prompt-reviews/regen/<YYYYMMDD-HHMM>-<model>/` instead:
 * one directory per model per run, holding that model's `.md` and the `run.log`
 * for it. Promoting a proposal to the current set is a deliberate copy, done by
 * hand after reading it. The layout is documented in `prompt-reviews/README.md`.
 */
const DEFAULT_REGEN_ROOT = join(
	here,
	"..",
	"..",
	"..",
	"..",
	"prompt-reviews",
	"regen",
);

/** One stamp for the whole invocation, so a run's models sort together. */
const RUN_STAMP = (() => {
	const now = new Date();
	const pad = (value: number) => String(value).padStart(2, "0");
	return [
		now.getFullYear(),
		pad(now.getMonth() + 1),
		pad(now.getDate()),
		"-",
		pad(now.getHours()),
		pad(now.getMinutes()),
	].join("");
})();

/**
 * The sampler this script imposes on every generation.
 *
 * Low, and deliberately so: the task is a one-shot transform of a document, not
 * a problem to explore, and a template is worth less the more it varies run to
 * run. Named here rather than written inline at the request so the provenance
 * header cannot claim a value the request did not send -- they read the same
 * constant.
 *
 * Everything this does NOT set is the tag's own sourced parameter, which is why
 * the header records both.
 */
const REQUEST_OPTIONS: Record<string, number> = { temperature: 0.2 };

function describeSampler(sampler: Record<string, number>): string[] {
	const keys = Object.keys(sampler);
	return keys.length === 0
		? ["       (none -- the tag's own parameters apply unchanged)"]
		: keys.map((key) => `       ${key} ${sampler[key]}`);
}

/**
 * Stamp the template with the model that actually wrote it.
 *
 * NOTHING used to write this header. It was model-written: the generator hands
 * a model its current template, that template opens with a provenance comment,
 * and the model copies the comment into its reply along with everything else.
 * Which means it was inherited, not observed -- and therefore wrong exactly
 * when it mattered.
 *
 * Measured on 2026-09-11: `deepseek.md` was generated by
 * `deepseek-v4.1-flash:cloud` against a live `family=deepseek_v41`, and came
 * back claiming `deepseek-v4-flash:cloud` and family `deepseek4`. The template
 * named the wrong model and the wrong family the moment it was written. In the
 * same run six of eight proposals carried no header at all, because a model
 * that rewrites the opening of the file simply drops it.
 *
 * So the script writes it, from the model id it called and the family
 * `/api/show` reported, and strips any header the model supplied first. A
 * model cannot report which model it is; the caller always can.
 */
function stampProvenance(
	raw: string,
	details: {
		model: string;
		family: string | undefined;
		/**
		 * True when the family was declared on the command line rather than read
		 * from `/api/show`. It decides which template seeded the rewrite, so a
		 * reader has to be able to tell a measured family from an asserted one.
		 */
		familyDeclared: boolean;
		sourced: string | undefined;
		runDir: string;
	},
): string {
	// Drop a model-supplied provenance block, wherever it put it.
	const stripped = raw.replace(/<!--[\s\S]*?-->\n*/g, (comment) =>
		/Written by/.test(comment) ? "" : comment,
	);
	// `.join("\n")` at the end of this literal makes it a string, not the array
	// it is built from; the annotation lagged the join and broke `bun run types`.
	const header: string = [
		"<!-- PROVENANCE -- written by scripts/review-prompt-templates.mts, not by the model.",
		"",
		`     Written by ${details.model} (${
			details.familyDeclared ? "family declared as" : "Ollama family"
		} \`${details.family ?? "unreported"}\`${
			details.familyDeclared ? ", because the tag reports none of its own" : ""
		}) on ${RUN_STAMP.slice(0, 4)}-${RUN_STAMP.slice(4, 6)}-${RUN_STAMP.slice(6, 8)}.`,
		`     Run, with its log: ${details.runDir.replace(/^.*?(?=prompt-reviews\/)/, "")}`,
		"",
		"     Sampler asked for by the generator, overriding the model's own:",
		...describeSampler(REQUEST_OPTIONS),
		"",
		"     Sampler the tag sources (`/api/show`), which applies to every key",
		"     the request above does not set:",
		...(details.sourced
			? details.sourced.split("\n").map((line) => `       ${line.trim()}`)
			: ["       (none reported)"]),
		"",
		"     The script hands a model the prompt it would really receive, names the",
		"     failures observed with models in its family, and asks for the version it",
		"     would rather read; the reply is parsed and audited before it lands here.",
		"",
		"     This line is stamped by the caller because a model cannot report which",
		"     model it is. Shown a template that opens with a header, a model copies",
		"     that header verbatim -- deepseek-v4.1-flash returned one naming",
		"     deepseek-v4-flash and family `deepseek4` while the live family was",
		"     `deepseek_v41`. Any header in a model's reply is stripped before this",
		"     one is added.",
		"",
		"     Regenerate rather than hand-edit, and audit a hand-edit with",
		"     scripts/audit-prompt-template.mts. -->",
	].join("\n");

	// After the frontmatter, before the first section.
	const end = stripped.indexOf("\n---\n", stripped.indexOf("---") + 1);
	if (!stripped.startsWith("---") || end === -1) {
		return `${header}\n\n${stripped}`;
	}
	const cut = end + "\n---\n".length;
	return `${stripped.slice(0, cut)}\n${header}\n${stripped.slice(cut).replace(/^\n+/, "\n")}`;
}

/**
 * Tees to the console and to the run folder's `run.log`.
 *
 * The log used to come from a shell redirection, which is why five of them
 * ended up loose in `prompt-reviews/`: the path was typed per invocation. The
 * script owns it now, so it lands beside the template it describes whether or
 * not anyone remembered to redirect.
 */
interface RunLog {
	log(line: string): void;
	warn(line: string): void;
	error(line: string): void;
	readonly text: string;
}

function createRunLog(): RunLog {
	const lines: string[] = [];
	const keep = (line: string) => {
		lines.push(line);
	};
	return {
		log(line) {
			console.log(line);
			keep(line);
		},
		warn(line) {
			console.warn(line);
			keep(line);
		},
		error(line) {
			console.error(line);
			keep(line);
		},
		get text() {
			return `${lines.join("\n")}\n`;
		},
	};
}

/**
 * Every cloud model a shipped family template is generated from.
 *
 * These are tags on Ollama's cloud, and they move: a family ships a new
 * flagship and the old tag stops resolving, which surfaces as a 404 from
 * `/api/chat` rather than as anything about templates. When that happens the
 * fix is here, and in the provenance header of the template it wrote.
 *
 * `claude.md` is not in this list. It is written against the same prompt by a
 * Claude, through a different provider, and audited the same way.
 */
const REVIEW_MODELS = [
	"gemma4:31b-cloud",
	"qwen3.5:397b-cloud",
	"glm-5.3:cloud",
	"deepseek-v4.1-flash:cloud",
	"kimi-k2.6:cloud",
	// Its own family, not a variant of the one above: `kimi-k3:cloud` reports
	// family `kimi-k3` and routes to `kimi-k3.md`. It was left out of this list
	// when the split was made, which is why `--all` silently regenerated nine
	// templates and left the tenth on whatever it last had.
	"kimi-k3:cloud",
	"minimax-m3:cloud",
	"nemotron-3-super:cloud",
];

/**
 * The two the templates were written for, so they review their own work first.
 * The rest of `REVIEW_MODELS` comes after these two have been checked by hand,
 * which is why `--all` is a flag rather than the default.
 */
const DEFAULT_MODELS = ["gemma4:31b-cloud", "qwen3.5:397b-cloud"];

/** A cloud model is a long call, and a rewrite of a 6KB prompt is a long one. */
const DEFAULT_TIMEOUT_MS = 600_000;

/**
 * How many times to hand a model its own mistakes back.
 *
 * A regeneration is cheap and a flawed template is expensive, so it is worth
 * spending calls to get a clean one. Three is enough in practice: a model that
 * cannot fix a duplicated heading on the second try is not going to.
 */
// Four, not three. The repair loop spends one attempt learning what the audit
// wants and one producing it; a model that also has to fix a name or a dropped
// placeholder runs out on the third. Measured 2026-09-12: minimax-m3 was still
// converging when it hit the limit, and gemma/deepseek/kimi all landed on
// attempt 2 -- so the extra attempt costs nothing on the models that work.
const DEFAULT_ATTEMPTS = 4;

/**
 * Tools a rewrite has to address, because the instructions name the failure
 * each one exists to prevent. Everything else is the model's call.
 */
const REQUIRED_MENTIONS = ["check_file", "code_intel"];

interface Options {
	models: string[];
	host: string;
	/** Where the per-model run directories go, not where a template goes. */
	regenRoot: string;
	timeoutMs: number;
	attempts: number;
	/** Extra tools a rewrite must address, on top of REQUIRED_MENTIONS. */
	require: string[];
	/**
	 * An explicit `model:` match for a template written from scratch.
	 *
	 * For a model reachable only through a params overlay: the overlay's name is
	 * scaffolding, and a match inferred from it claims the scaffolding rather
	 * than the family the template is for.
	 */
	matchModel: string[];
	/** An explicit `family:` match, for a generational split (kimi-k2 vs kimi-k3). */
	matchFamily: string[];
	/** The template's name, when the split means it is no longer the one shown. */
	name?: string;
	/**
	 * Leave the model's reasoning on for this run.
	 *
	 * Off is right for most: a one-shot transform is not a problem to reason
	 * about, and a reasoning model spends the whole budget on the thinking
	 * block. But `think: false` is a request, not a guarantee, and a model that
	 * declines it does not stop reasoning -- it stops *separating* the
	 * reasoning, and the prose lands in `content` where the template should be.
	 * Measured on `glm-5.3-tpl:latest`, same prompt, same sampler:
	 *
	 *   think on   -> thinking 2,978 chars, content 46 chars, exactly the
	 *                 template asked for
	 *   think off  -> thinking 0, content 1,598 chars, all of it reasoning
	 *
	 * That is every glm attempt across two days of "does not parse: no
	 * '# system' or '# tool:' section" -- the file was reasoning, not a
	 * template. For such a model the reasoning has to stay in its own block,
	 * and the cost is a longer call, so raise `--timeout` with it.
	 */
	think?: boolean;
	/**
	 * The family this model stands in for, when it cannot report one itself.
	 *
	 * A params-only overlay built `FROM` a cloud tag carries no weights, so
	 * `/api/show` answers `family: ""` for it. The family is what decides which
	 * template seeds the rewrite, so an overlay with none is handed `default.md`
	 * instead of its own family's file -- measured on `glm-5.3-tpl:latest`,
	 * which was seeded from `default.md` on every attempt across two days and
	 * never produced a parsable template. Declaring it here is the difference
	 * between reviewing the glm template and reviewing the base prompt.
	 */
	family?: string;
}

function parseArgs(argv: string[]): Options {
	const models: string[] = [];
	let host = process.env.OLLAMA_HOST ?? "http://localhost:11434";
	let regenRoot = DEFAULT_REGEN_ROOT;
	let timeoutMs = DEFAULT_TIMEOUT_MS;
	let attempts = DEFAULT_ATTEMPTS;
	const require: string[] = [];
	const matchModel: string[] = [];
	const matchFamily: string[] = [];
	let name: string | undefined;
	let family: string | undefined;
	let think = false;

	for (let index = 0; index < argv.length; index++) {
		const arg = argv[index];
		const value = argv[index + 1];
		switch (arg) {
			case "--think":
				think = true;
				break;
			case "--family":
				if (!value) {
					throw new Error("--family needs a family name");
				}
				family = value;
				index++;
				break;
			case "--match-family":
				if (!value) {
					throw new Error("--match-family needs a pattern");
				}
				matchFamily.push(value);
				index++;
				break;
			case "--name":
				if (!value) {
					throw new Error("--name needs a template name");
				}
				name = value;
				index++;
				break;
			case "--match-model":
				if (!value) {
					throw new Error("--match-model needs a glob, e.g. '*minimax*'");
				}
				matchModel.push(value);
				index++;
				break;
			case "--all":
				models.push(...REVIEW_MODELS);
				break;
			case "--model":
				if (!value) {
					throw new Error("--model needs a model name");
				}
				models.push(value);
				index++;
				break;
			case "--host":
				if (!value) {
					throw new Error("--host needs a URL");
				}
				host = value;
				index++;
				break;
			// The regen *root*. A run still makes its own
			// `<stamp>-<model>/` underneath it -- there is no flag that
			// writes a proposal loose in a directory, on purpose.
			case "--out":
				if (!value) {
					throw new Error("--out needs a directory");
				}
				regenRoot = value;
				index++;
				break;
			case "--timeout":
				if (!value) {
					throw new Error("--timeout needs seconds");
				}
				timeoutMs = Number(value) * 1000;
				index++;
				break;
			case "--require":
				if (!value) {
					throw new Error("--require needs a tool name");
				}
				require.push(value);
				index++;
				break;
			case "--attempts":
				if (!value) {
					throw new Error("--attempts needs a number");
				}
				attempts = Math.max(1, Math.trunc(Number(value)));
				index++;
				break;
			default:
				throw new Error(`unknown argument ${arg}`);
		}
	}

	if (!host.startsWith("http")) {
		host = `http://${host}`;
	}
	return {
		models: models.length > 0 ? models : DEFAULT_MODELS,
		host: host.replace(/\/+$/, ""),
		regenRoot,
		timeoutMs,
		attempts,
		require,
		matchModel,
		matchFamily,
		name,
		family,
		think,
	};
}

async function post(
	host: string,
	path: string,
	body: unknown,
	timeoutMs: number,
): Promise<unknown> {
	const controller = new AbortController();
	const timer = setTimeout(() => controller.abort(), timeoutMs);
	try {
		const response = await fetch(`${host}${path}`, {
			method: "POST",
			headers: { "content-type": "application/json" },
			body: JSON.stringify(body),
			signal: controller.signal,
		});
		if (!response.ok) {
			throw new Error(`${path} returned ${response.status}`);
		}
		return await response.json();
	} finally {
		clearTimeout(timer);
	}
}

/**
 * What the model actually is, which is what a template matches on.
 *
 * A cloud model answers `/api/show` the same way a local one does, so the
 * review runs against the template the model would really be given rather
 * than one picked from its name.
 */
/**
 * What the model reports about itself, recorded in the template it writes.
 *
 * The family is what routing keys on. The sampler matters for a different
 * reason: these templates are prose written by a model, and prose is a sampled
 * output. A template written at the model's own `temperature 0.6` is not the
 * same artifact as one written at the `0.2` this script asks for, and a tag
 * whose Modelfile sets `repeat_penalty` or `presence_penalty` is writing under
 * pressure that shapes how it phrases a rule. None of that is recoverable from
 * the file afterwards unless it is written down at the time -- and these cloud
 * tags carry different sourced parameters from each other: `igovet/...` tags
 * exist precisely because a stock tag's parameters truncated the reply.
 */
interface ModelFacts {
	family: string | undefined;
	/** The model's own sourced parameters, as `/api/show` reports them. */
	sourced: string | undefined;
}

async function readModelFacts(
	host: string,
	model: string,
	timeoutMs: number,
	runLog: RunLog,
): Promise<ModelFacts> {
	try {
		const payload = (await post(host, "/api/show", { model }, timeoutMs)) as {
			details?: { family?: string };
			model_info?: Record<string, unknown>;
			parameters?: string;
		};
		const family =
			payload.details?.family ??
			(payload.model_info?.["general.architecture"] as string | undefined);
		const sourced =
			typeof payload.parameters === "string" && payload.parameters.trim() !== ""
				? payload.parameters.trim()
				: undefined;
		return {
			family:
				typeof family === "string" && family.trim() !== ""
					? family.trim()
					: undefined,
			sourced,
		};
	} catch (error) {
		runLog.warn(
			`  could not read /api/show for ${model}: ${
				error instanceof Error ? error.message : String(error)
			}`,
		);
		return { family: undefined, sourced: undefined };
	}
}

async function review(model: string, options: Options): Promise<boolean> {
	const runLog = createRunLog();
	runLog.log(`\n${model}`);

	const facts = await readModelFacts(
		options.host,
		model,
		options.timeoutMs,
		runLog,
	);
	// The declaration wins over what the tag reports, because the only reason to
	// pass it is that the tag reports nothing usable. Kept separate from `facts`
	// so the provenance header can say which of the two it was.
	const family = options.family ?? facts.family;
	const templates = getBuiltinPromptTemplates();
	const rendered = renderPromptTemplate(templates, {
		providerId: "ollama",
		modelId: model,
		family,
	});
	const matchedName = rendered?.name;
	const isDefault =
		matchedName === undefined ||
		matchedName.toLowerCase() === DEFAULT_PROMPT_TEMPLATE_NAME;
	runLog.log(
		`  family=${family ?? "unknown"}${
			options.family
				? ` (declared; /api/show reported ${facts.family ?? "none"})`
				: ""
		} template=${matchedName ?? "none"}`,
	);

	const defaultTemplate = readFileSync(
		join(TEMPLATE_DIR, "default.md"),
		"utf8",
	);
	const familyFileName = isDefault
		? undefined
		: templates.find((template) => template.name === matchedName)?.fileName;
	const familyTemplate = familyFileName
		? readFileSync(join(TEMPLATE_DIR, familyFileName), "utf8")
		: undefined;

	// Every tool a session can be handed. Without this the parser cannot tell a
	// section naming a real tool from one naming a tool the model invented.
	const knownToolNames = Object.keys(
		templates.find(
			(template) =>
				template.name.toLowerCase() === DEFAULT_PROMPT_TEMPLATE_NAME,
		)?.tools ?? {},
	);

	const slug = model.replace(/[^a-zA-Z0-9._-]/g, "-");
	const runDir = join(options.regenRoot, `${RUN_STAMP}-${slug}`);
	const outputPath = join(runDir, `${slug}.md`);
	const logPath = join(runDir, "run.log");
	mkdirSync(runDir, { recursive: true });

	try {
		const result = await generatePromptTemplate({
			defaultTemplate,
			familyTemplate,
			familyFileName,
			providerId: "ollama",
			modelId: model,
			family,
			knownToolNames,
			// The real argument shapes, so every example call the model writes is
			// audited against the schema it will actually be sent.
			toolSignatures: getShippedToolCallSignatures(),
			requiredMentions: [...REQUIRED_MENTIONS, ...options.require],
			expectedName: options.name ?? (isDefault ? undefined : matchedName),
			matchModel: options.matchModel,
			matchFamily: options.matchFamily,
			fileName: `${slug}.md`,
			attempts: options.attempts,
			complete: async (messages) => {
				const payload = (await post(
					options.host,
					"/api/chat",
					{
						model,
						stream: false,
						// This is a one-shot transform, not a problem to reason
						// about, and a reasoning model spends the whole budget
						// on the thinking block: deepseek-v4-flash times out at
						// forty minutes with it on and answers in two with it
						// off. The in-app generator disables reasoning for the
						// same reason; ignored by models that have none.
						//
						// `--think` overrides it, because "ignored" is not the
						// only other outcome: a model can decline to separate
						// its reasoning and write it into `content` instead,
						// which produces a file of prose and an audit that
						// says the file does not parse. See `Options.think`.
						think: options.think ?? false,
						options: REQUEST_OPTIONS,
						messages,
					},
					options.timeoutMs,
				)) as { message?: { content?: string } };
				return payload.message?.content ?? "";
			},
			onAttempt: (attempt, problems) => {
				for (const problem of problems) {
					runLog.warn(`  attempt ${attempt}: ${problem}`);
				}
			},
		});

		writeFileSync(
			outputPath,
			`${stampProvenance(result.raw, {
				model,
				family,
				familyDeclared: options.family !== undefined,
				sourced: facts.sourced,
				runDir,
			})}\n`,
			"utf8",
		);
		if (result.audit.problems.length === 0) {
			runLog.log(
				`  clean on attempt ${result.attempts}: system=${
					result.audit.template?.system ? "yes" : "no"
				} tools=${Object.keys(result.audit.template?.tools ?? {}).join(", ") || "none"}`,
			);
			runLog.log(`  wrote ${outputPath}`);
			writeFileSync(logPath, runLog.text, "utf8");
			return true;
		}
		runLog.error(
			`  NOT CLEAN after ${result.attempts} attempt(s); wrote the best of them to ${outputPath}`,
		);
		writeFileSync(logPath, runLog.text, "utf8");
		return false;
	} catch (error) {
		runLog.error(
			`  failed: ${error instanceof Error ? error.message : String(error)}`,
		);
		// A run that produced no template still keeps its log: the reason it
		// produced none is the whole value of the directory.
		writeFileSync(logPath, runLog.text, "utf8");
		return false;
	}
}

async function main(): Promise<void> {
	const options = parseArgs(process.argv.slice(2));
	console.log(`host=${options.host} regen=${options.regenRoot}`);

	let clean = true;
	for (const model of options.models) {
		// Sequential on purpose: these are large models on a shared endpoint,
		// and two of them at once is how one of them times out.
		clean = (await review(model, options)) && clean;
	}

	console.log(
		`\nProposals are in ${options.regenRoot}/${RUN_STAMP}-*. Nothing was copied into prompt-reviews/ or assets/prompt-templates. Read a proposal, and promote it by hand if it is better.`,
	);
	process.exit(clean ? 0 : 1);
}

await main();
