// Generated by `sdk/packages/core/scripts/lancedb-manifest.mjs` from a resolved
// install of @lancedb/lancedb and apache-arrow. Do not edit by hand: the
// integrity values are what the installer checks each download against.

export interface LanceDbRuntimePackage {
	/** Where it is unpacked, relative to the runtime folder. */
	path: string;
	tarball: string;
	/** `sha512-<base64>`, as npm records it. */
	integrity: string;
	unpackedBytes?: number;
}

export interface LanceDbRuntimeManifest {
	version: string;
	arrow: string;
	/** The JavaScript packages, the same on every platform. */
	packages: LanceDbRuntimePackage[];
	/** The native library, by `<platform>-<arch>` with `-gnu`/`-musl` on Linux. */
	platforms: Record<string, LanceDbRuntimePackage>;
}

export const LANCEDB_RUNTIME_MANIFEST: LanceDbRuntimeManifest = {
	version: "0.39.0",
	arrow: "18.1.0",
	packages: [
		{
			path: "node_modules/@lancedb/lancedb",
			tarball:
				"https://registry.npmjs.org/@lancedb/lancedb/-/lancedb-0.39.0.tgz",
			integrity:
				"sha512-mcHi7/G2knZVj7OUya1vcMAjbHEqcait31cXINdUzQrru+ulo9Rks35T5XQpHQXI/P+6o10azATBtNa0u2tDCA==",
		},
		{
			path: "node_modules/@opentelemetry/api",
			tarball: "https://registry.npmjs.org/@opentelemetry/api/-/api-1.9.1.tgz",
			integrity:
				"sha512-gLyJlPHPZYdAk1JENA9LeHejZe1Ti77/pTeFm/nMXmQH/HFZlcS/O2XJB+L8fkbrNSqhdtlvjBVjxwUYanNH5Q==",
		},
		{
			path: "node_modules/@swc/helpers",
			tarball: "https://registry.npmjs.org/@swc/helpers/-/helpers-0.5.23.tgz",
			integrity:
				"sha512-5lSsMOTXURePglDfvuAQUqkGek9Hg2kksOYay2m0+XR++b2NWYL/4sWyuvVBIs8oKnJaxkdi9whaL/sqN13afw==",
		},
		{
			path: "node_modules/ansi-styles",
			tarball: "https://registry.npmjs.org/ansi-styles/-/ansi-styles-4.3.0.tgz",
			integrity:
				"sha512-zbB9rCJAT1rbjiVDb2hqKFHNYLxgtk8NURxZ3IZwD3F6NtxbXZQCnnSi1Lkx+IDohdPlFp222wVALIheZJQSEg==",
		},
		{
			path: "node_modules/apache-arrow",
			tarball:
				"https://registry.npmjs.org/apache-arrow/-/apache-arrow-18.1.0.tgz",
			integrity:
				"sha512-v/ShMp57iBnBp4lDgV8Jx3d3Q5/Hac25FWmQ98eMahUiHPXcvwIMKJD0hBIgclm/FCG+LwPkAKtkRO1O/W0YGg==",
		},
		{
			path: "node_modules/array-back",
			tarball: "https://registry.npmjs.org/array-back/-/array-back-3.1.0.tgz",
			integrity:
				"sha512-TkuxA4UCOvxuDK6NZYXCalszEzj+TLszyASooky+i742l9TqsOdYCMJJupxRic61hwquNtppB3hgcuq9SVSH1Q==",
		},
		{
			path: "node_modules/chalk",
			tarball: "https://registry.npmjs.org/chalk/-/chalk-4.1.2.tgz",
			integrity:
				"sha512-oKnbhFyRIXpUuez8iBMmyEa4nbj4IOQyuhc/wy9kY7/WVPcwIO9VA668Pu8RkO7+0G76SLROeyw9CpQ061i4mA==",
		},
		{
			path: "node_modules/chalk-template",
			tarball:
				"https://registry.npmjs.org/chalk-template/-/chalk-template-0.4.0.tgz",
			integrity:
				"sha512-/ghrgmhfY8RaSdeo43hNXxpoHAtxdbskUHjPpfqUWGttFgycUhYPGx3YZBCnUCvOa7Doivn1IZec3DEGFoMgLg==",
		},
		{
			path: "node_modules/color-convert",
			tarball:
				"https://registry.npmjs.org/color-convert/-/color-convert-2.0.1.tgz",
			integrity:
				"sha512-RRECPsj7iu/xb5oKYcsFHSppFNnsj/52OVTRKb4zP5onXwVF3zVmmToNcOfGC+CRDpfK/U584fMg38ZHCaElKQ==",
		},
		{
			path: "node_modules/color-name",
			tarball: "https://registry.npmjs.org/color-name/-/color-name-1.1.4.tgz",
			integrity:
				"sha512-dOy+3AuW3a2wNbZHIuMZpTcgjGuLU/uBL/ubcZF9OXbDo8ff4O8yVp5Bf0efS8uEoYo5q4Fx7dY9OgQGXgAsQA==",
		},
		{
			path: "node_modules/command-line-args",
			tarball:
				"https://registry.npmjs.org/command-line-args/-/command-line-args-5.2.1.tgz",
			integrity:
				"sha512-H4UfQhZyakIjC74I9d34fGYDwk3XpSr17QhEd0Q3I9Xq1CETHo4Hcuo87WyWHpAF1aSLjLRf5lD9ZGX2qStUvg==",
		},
		{
			path: "node_modules/command-line-usage",
			tarball:
				"https://registry.npmjs.org/command-line-usage/-/command-line-usage-7.0.4.tgz",
			integrity:
				"sha512-85UdvzTNx/+s5CkSgBm/0hzP80RFHAa7PsfeADE5ezZF3uHz3/Tqj9gIKGT9PTtpycc3Ua64T0oVulGfKxzfqg==",
		},
		{
			path: "node_modules/command-line-usage/node_modules/array-back",
			tarball: "https://registry.npmjs.org/array-back/-/array-back-6.2.3.tgz",
			integrity:
				"sha512-SGDvmg6QTYiTxCBkYVmThcoa67uLl35pyzRHdpCGBOcqFy6BtwnphoFPk7LhJshD+Yk1Kt35WGWeZPTgwR4Fhw==",
		},
		{
			path: "node_modules/command-line-usage/node_modules/typical",
			tarball: "https://registry.npmjs.org/typical/-/typical-7.3.0.tgz",
			integrity:
				"sha512-ya4mg/30vm+DOWfBg4YK3j2WD6TWtRkCbasOJr40CseYENzCUby/7rIvXA99JGsQHeNxLbnXdyLLxKSv3tauFw==",
		},
		{
			path: "node_modules/find-replace",
			tarball:
				"https://registry.npmjs.org/find-replace/-/find-replace-3.0.0.tgz",
			integrity:
				"sha512-6Tb2myMioCAgv5kfvP5/PkZZ/ntTpVK39fHY7WkWBgvbeE+VHd/tZuZ4mrC+bxh4cfOZeYKVPaJIZtZXV7GNCQ==",
		},
		{
			path: "node_modules/flatbuffers",
			tarball:
				"https://registry.npmjs.org/flatbuffers/-/flatbuffers-24.12.23.tgz",
			integrity:
				"sha512-dLVCAISd5mhls514keQzmEG6QHmUUsNuWsb4tFafIUwvvgDjXhtfAYSKOzt5SWOy+qByV5pbsDZ+Vb7HUOBEdA==",
		},
		{
			path: "node_modules/has-flag",
			tarball: "https://registry.npmjs.org/has-flag/-/has-flag-4.0.0.tgz",
			integrity:
				"sha512-EykJT/Q1KjTWctppgIAgfSO0tKVuZUjhgMr17kqTumMl6Afv3EISleU7qZUzoXDFTAHTDC4NOoG/ZxU3EvlMPQ==",
		},
		{
			path: "node_modules/json-bignum",
			tarball: "https://registry.npmjs.org/json-bignum/-/json-bignum-0.0.3.tgz",
			integrity:
				"sha512-2WHyXj3OfHSgNyuzDbSxI1w2jgw5gkWSWhS7Qg4bWXx1nLk3jnbwfUeS0PSba3IzpTUWdHxBieELUzXRjQB2zg==",
		},
		{
			path: "node_modules/lodash.camelcase",
			tarball:
				"https://registry.npmjs.org/lodash.camelcase/-/lodash.camelcase-4.3.0.tgz",
			integrity:
				"sha512-TwuEnCnxbc3rAvhf/LbG7tJUDzhqXyFnv3dtzLOPgCG/hODL7WFnsbwktkD7yUV0RrreP/l1PALq/YSg6VvjlA==",
		},
		{
			path: "node_modules/reflect-metadata",
			tarball:
				"https://registry.npmjs.org/reflect-metadata/-/reflect-metadata-0.2.2.tgz",
			integrity:
				"sha512-urBwgfrvVP/eAyXx4hluJivBKzuEbSQs9rKWCrCkbSxNv8mxPcUZKeuoF3Uy4mJl3Lwprp6yy5/39VWigZ4K6Q==",
		},
		{
			path: "node_modules/supports-color",
			tarball:
				"https://registry.npmjs.org/supports-color/-/supports-color-7.2.0.tgz",
			integrity:
				"sha512-qpCAvRl9stuOHveKsn7HncJRvv501qIacKzQlO/+Lwxc9+0q2wLyv4Dfvt80/DPn2pqOBsJdDiogXGR9+OvwRw==",
		},
		{
			path: "node_modules/table-layout",
			tarball:
				"https://registry.npmjs.org/table-layout/-/table-layout-4.1.1.tgz",
			integrity:
				"sha512-iK5/YhZxq5GO5z8wb0bY1317uDF3Zjpha0QFFLA8/trAoiLbQD0HUbMesEaxyzUgDxi2QlcbM8IvqOlEjgoXBA==",
		},
		{
			path: "node_modules/table-layout/node_modules/array-back",
			tarball: "https://registry.npmjs.org/array-back/-/array-back-6.2.3.tgz",
			integrity:
				"sha512-SGDvmg6QTYiTxCBkYVmThcoa67uLl35pyzRHdpCGBOcqFy6BtwnphoFPk7LhJshD+Yk1Kt35WGWeZPTgwR4Fhw==",
		},
		{
			path: "node_modules/tslib",
			tarball: "https://registry.npmjs.org/tslib/-/tslib-2.8.1.tgz",
			integrity:
				"sha512-oJFu94HQb+KVduSUQL7wnpmqnfmLsOA/nAh6b6EH0wCEoK0/mPeXU6c3wKDV83MkOuHPRHtSXKKU99IBazS/2w==",
		},
		{
			path: "node_modules/typical",
			tarball: "https://registry.npmjs.org/typical/-/typical-4.0.0.tgz",
			integrity:
				"sha512-VAH4IvQ7BDFYglMd7BPRDfLgxZZX4O4TFcRDA6EN5X7erNJJq+McIEp8np9aVtxrCJ6qx4GTYVfOWNjcqwZgRw==",
		},
		{
			path: "node_modules/wordwrapjs",
			tarball: "https://registry.npmjs.org/wordwrapjs/-/wordwrapjs-5.1.1.tgz",
			integrity:
				"sha512-0yweIbkINJodk27gX9LBGMzyQdBDan3s/dEAiwBOj+Mf0PPyWL6/rikalkv8EeD0E8jm4o5RXEOrFTP3NXbhJg==",
		},
	],
	platforms: {
		"linux-x64-gnu": {
			path: "node_modules/@lancedb/lancedb-linux-x64-gnu",
			tarball:
				"https://registry.npmjs.org/@lancedb/lancedb-linux-x64-gnu/-/lancedb-linux-x64-gnu-0.39.0.tgz",
			integrity:
				"sha512-CJz2Dm2rPSFQSGWIllWt4PYgz2JsdAlz1fNzm8AFkxIhQwO30/kxtbRqzs4rqptQOtGUxlaIIeSipsANov1cKA==",
			unpackedBytes: 202093186,
		},
		"linux-x64-musl": {
			path: "node_modules/@lancedb/lancedb-linux-x64-musl",
			tarball:
				"https://registry.npmjs.org/@lancedb/lancedb-linux-x64-musl/-/lancedb-linux-x64-musl-0.39.0.tgz",
			integrity:
				"sha512-S6oCxSEnwD6L7lmcoxnLSYJMVUMx57dPYKMwv1MtY/Bv4+VIgmCg8u0HTtXzJrrHnowtuhjtTqptu/7O41ZXsw==",
			unpackedBytes: 168057381,
		},
		"linux-arm64-gnu": {
			path: "node_modules/@lancedb/lancedb-linux-arm64-gnu",
			tarball:
				"https://registry.npmjs.org/@lancedb/lancedb-linux-arm64-gnu/-/lancedb-linux-arm64-gnu-0.39.0.tgz",
			integrity:
				"sha512-WMoIED9D4XScRVgB0Da1DTW0PHP0apzUUYbcA0XYJgZ/kzHhFBigCtiOksMIVTT31SRXLsyX00AYRys3VyrEmQ==",
			unpackedBytes: 389044893,
		},
		"linux-arm64-musl": {
			path: "node_modules/@lancedb/lancedb-linux-arm64-musl",
			tarball:
				"https://registry.npmjs.org/@lancedb/lancedb-linux-arm64-musl/-/lancedb-linux-arm64-musl-0.39.0.tgz",
			integrity:
				"sha512-46K+pDQ88prIpYjx+mRpxJoy1kaeZJneJAOGSTlEneB7pA155wNggr7VwXm+cQeyjp2uuS0BzgWAiN4RGD9Bgg==",
			unpackedBytes: 255852688,
		},
		"darwin-arm64": {
			path: "node_modules/@lancedb/lancedb-darwin-arm64",
			tarball:
				"https://registry.npmjs.org/@lancedb/lancedb-darwin-arm64/-/lancedb-darwin-arm64-0.39.0.tgz",
			integrity:
				"sha512-8MtalZRx8Ks/vED1jydXLuSlgJKmAtY2Cn9nuZo6RpgNtDxbB6dhdoF3gWhhbsRUOiETzHkmPukR53yfk8A/LQ==",
			unpackedBytes: 239096008,
		},
		"win32-x64": {
			path: "node_modules/@lancedb/lancedb-win32-x64-msvc",
			tarball:
				"https://registry.npmjs.org/@lancedb/lancedb-win32-x64-msvc/-/lancedb-win32-x64-msvc-0.39.0.tgz",
			integrity:
				"sha512-HE8aD11DSElESGYBaTuy9Pvcapg1vRIK2qAsZVGPGN1AVUOI3j304UdVJiHQqY+cSwPs0DvBv9rkbsewY9XAOQ==",
			unpackedBytes: 316571103,
		},
		"win32-arm64": {
			path: "node_modules/@lancedb/lancedb-win32-arm64-msvc",
			tarball:
				"https://registry.npmjs.org/@lancedb/lancedb-win32-arm64-msvc/-/lancedb-win32-arm64-msvc-0.39.0.tgz",
			integrity:
				"sha512-ZGVJEPVXnl1dWDs+LHR4AW0x9XmCBjch8eHz/iJL1q+niAbaDaBx66QAt4DMBp3zxMxCS8oDB6nwUm6/UEpFsg==",
			unpackedBytes: 269388266,
		},
	},
};
